baseURL = "//janraasch.com/"
languageCode = "en-us"
title = "janraasch"
theme="hugo-split-theme"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2019 Jan Raasch"

[params]

  # Metadata for search engines and social sharing
  author = "Jan Raasch"
  description = "Jan Martin Raasch's Website"
  shareImage = "images/social.jpg"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/jan-raasch-background.jpg"
      position = "center center"
  [[params.links]]

  [params.links.list1]
    heading = "Connect"

    [[params.links.list1.link]]
      text = "Email"
      url = "mailto:jan@janraasch.com"

    [[params.links.list1.link]]
      text = "Github"
      url = "https://github.com/janraasch/"
