baseURL = "//dennishoertinger.eu/"
languageCode = "en-us"
title = "dennis"
theme="hugo-split-theme"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Copyright
copyright = "&copy;2019 Jan Raasch"

[params]

  # Metadata for search engines and social sharing
  author = "Dennis Hörtinger"
  description = "Dennis Hörtinger's Website"
  shareImage = "images/social.jpg"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/dennis-hoertinger-background.gif"
      position = "center center"
  [[params.links]]

  [params.links.list1]
    heading = "Connect"

    [[params.links.list1.link]]
      text = "Email"
      url = "mailto:dennishoertinger@gmail.com"

    [[params.links.list1.link]]
      text = "Behance"
      url = "https://github.com/janraasch/"
